CREATE TABLE eventos(

     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     nome VARCHAR(255) NOT NULL,
     descricao TEXT,
     identificador VARCHAR(255) UNIQUE NOT NULL,
     local_evento VARCHAR(255) NOT NULL,
     organizador VARCHAR(255) NOT NULL,
     capacidade INTEGER NOT NULL,
     data_inicio TIMESTAMP NOT NULL,
     data_fim TIMESTAMP NOT NULL,
     tipo_eventos VARCHAR(255)




)